# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'permissions': (('is_manager', 'Users manager (allowed all CRUD operations on users list)'), ('is_admin', 'Full access administrator (allowed all CRUD operations on users & times list)'))},
        ),
        migrations.AlterField(
            model_name='time',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
