# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_auto_20160620_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ('-date', '-id'), 'permissions': (('is_manager', 'Users manager (allowed all CRUD operations on users list)'), ('is_admin', 'Full access administrator (allowed all CRUD operations on users & times list)'))},
        ),
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateField(),
        ),
    ]
